Repository sort-font/webpage, pull requests merged in 2021-09, with the labels that each got.

#43 判定後に一覧ページに遷移するように修正
  templates/index.html
  templates/result.html
  templates/top.html
Labels: バグ

#47 Internal Server Errorの原因となっていたディレクトリを追加
  server.py
  static/images/.gitkeep
Labels: バグ

#49 GitHub ActionsのLinterを追加
  .github/workflows/ci.yml
Labels: 新規機能

#60 Star rating
  server.py
  static/css/style.css
  templates/enter.html
  templates/result.html
Labels: フロント

#41 各エンドポイントのテストコードを追加する
  Makefile
  requirements.txt
  test_server.py
Labels: 新規機能
